dist: trusty
jdk: oraclejdk8
language: java
sudo: true
services:
  - postgresql
  - docker
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}
script:
  - ./mvnw clean install -B
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
  - export IMAGE_NAME=myapi/main-repo
  - docker build -t $IMAGE_NAME:latest .
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: myapi-api