dist: trusty
jdk: oraclejdk8
language: java
sudo: true
services:
  - postgresql
  - docker
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer
#before_install:
#  - chmod +x mvnw
env:
  global:
    - secure: "DIZr0/EhC5kpErRHi03PuwOPpoktK5w84jEB+ts4GmNnb9PohoA+cNpRxJal81A0l3t689IAMqjQ1M02JbXrlFIX0QwzFCb8jsBIYskj9Na5YfkA85MgVQj2B6EsIjJ18QrDH1CVWVbjCgX77qLcSNQaLVwpSEyA65nrNb6FFc7DBKnVjhtebP7C6GDXLmR8nF9zxCiWrsD4wF46xEz450Un9Fljwk11RuqYkEFLYyC7OsRjw+HhOWAFIxnbcO8fb0ojE3r7D79JATWyDJPr2iBWfdJkz2yn594UlcoxzLMhkrA4hm+hgYsUyheDoDhLdXT/ySb6wR18ZpuoKHwXPcfETxAVuakrtSf47Rxn6/w6DyK1GVi6G4nYSqmYPCFY2mhuKTHdHgF6DgmjTaPpeGZYtPMjr5inT4KNNdI1fdXjxdXXLt7KuEW9ZLQtaW23uFe/sahlEXl19v+XrY2Ei8E8mPB2dk3x8cwT1gm+0EAEGBsDVA7xaFBG53cG/baqsSQ5v0K3N7lce2vPe1k83S1GQAZuTCVN+zXW4+4vHw9G2oSAmQChFV6zFZWh9aVPqnVQ+7LMzrD1X9yXklHVMVrw6kK+Eq8EmY4mmf5hTEWO1xYPm3MaeNSSoOlLQAD7fBTtOp3mme/B4Vo8VMvjDKxv/GDcyvrJaJ6mXh3Iasw="
    - secure: "mKinYbVzkeOAvdj8SfU3+YesM6QGoSFSTmsoC1ofpk3lLmnWmwI6KbKbu6e/tlCbplYO+sDRiSWg20zWEU7qvIpknNq6S/vsOE+qbaCh94crHZAS1ovdjQPH0HQ/Pwqy1T0/Td81Fp028NprWhhU6fw82Im3sFIV/85MworU2Pcg81JnOI9beZh6q4d5QI61g9y1wb5UH0KPEQzW/jcG/wxowBv/MHHf5ZqYAv84SuUnkJsh9t+WGVfR4c5yuAlsZdwHmDrDSjeQHdaY4KnC689+WdvszRIZbyy3b32LJAtJ6dxm/XG/5hqNkuOFYeNV5H1TntNzwJ5PbE7AE9HeIKz0ONsDkc/F/j2M6OmXU1R2cC99ZSdmo7orXhUsb+gLNuL+5BdNSda3e72We5HR8W2JfCYRvvY6LD+q+Jziqh2xoScXydshrYDOywDIYhSaF4D5ESazsmp16s/+mF36d9qpa2PhhhrzoBY0Pcikngyvuaq2ZdFrZqAjdDY3N8kYNB9VUf1s8aOJ+UIYcZbGSUV+wbWVC2KwuguB/bQ8RAcJgqskt3zum0aVj3wHYbHsNlHvCzHpAOdqn1pJn4yuYQ8RqVUTfk0b1LDF2NIJb8VyALG1SXxwzYqUUWels+HhX2pR5yJ0VIqhlTGdN6QG/0jfRzJvG/cIMQ+11+2pYDU="
    - secure: "GSWXSEmbMu3ZDQj8loffBQJJ4vXW52p+vacCyHWlCGP/ZMNJkYaCqk40ITtyd5j/ZD3yh2QCld56pNvNlKnC+Wt1tEhZ1T1e/DdgenlNgCzDr/jzxcIJJzSsSmJ9Dcx8TjxdWVYrVqlx+h4XhSxCQKayvdv8TmQpVnd/I1ty5R/RGAK+S4lA/uMFRJ3dyLiSA8gO8ShsJlv+0K6jDRx0Px2iGPMqIpZiObByutlg3CHMlRYdeQ0u7Marwa8ghY5Vaq0ANvTfr0qoFhMwzUzBnOUqtY8R9b6pqyqtSY7gWdd2nn/EV4Q6cJ03XM6FVbHaGCyKkQnQ9LCvsyjeND8+WNrmBxbB7Y4FMLR0pZxH0vi2U15pUcTSPDbZTD48+jz8bXaOAWV7+lokTLGpkglQ3yPNDnDIKzF64V9cRlU6RY8twKWKK+muf1kIBOVKZrNXMhU5RMyGjy4YTvzJgE0CGOq1PjvebeKZPBNSp4f5+qdxwmrcIva4HgL0nMED2vdbVUdrRJQEHzswdUvxG4MVF28HBh+CULSYwSBNTCZ+9tnnGVVvINYEIiUyJSNlfdEsTBZpefHJqhJUu/KznTelmzQ9/wxtz3lkXZyAOtKr2YEFp0fsyWXyH+VQ7CiP6cIbG5RyF0elg0CgMmtdcVcpRXBjMG83/MtJmRV6EnrpQE4="
    - COMMIT=${TRAVIS_COMMIT::7}
script:
  - ./mvnw clean install -B
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
  - export IMAGE_NAME=myapi/main-repo
  - docker build -t $IMAGE_NAME:latest .
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: myapi-api