dist: trusty
jdk: oraclejdk8
language: java
sudo: true
services:
  - postgresql
  - docker
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
env:
  global:
    - secure: "uNPltK5OgyDnwva+TtOzWY7E2EOD0g2KipjhjcWijyFmBbasLLhi33xJnQzxigc11Bs9d646Yu8Yu8nLCp2+IS3NcMyedHs3q4fOq+Z6QUK2x5g1jLJCmKMZGEuI4jyM+msHH46GkEWyV1QOZEJeSBTWduRQYmDe0Io5liNR5oI01LZOc6Z53RrIQXDA1/bqyjh8z4tRvOI5tZXU2UDtc1XVmqtnmbAnijRGfndtfJYs9fW5wbieP/jOkrgaI9UWmfXtf/0nT87AqMMHyVVlQkUrsf0sHSAhx80dEbwfQV9+ybj+gBhJSQR0m7b1UxHfatHzvs/FUWVrP5Vw/Icov9eGetIvkwpBnAWgu3dpBrmuQHGb5N0pGCRtXqYB8K0lejmLDg7XLk9UgVZlfNMp1CZWX9cCB8qh78d8BCTlCUEioMwRfYjCMb1/DazLoo39bUY/YxGoL20aGvuMLqskSmz+2vhAqPCri/4i4eta5b0sfCAtv0wL3uRJynk2dDNtWXzUBtD+qIjnB/gUKiHWC2u0To2mvxLWeYDEGSWkRcV6H1nH59fWOjPTsxFvULJaR4k9IYaWQkyzmPZPoh21KLPodw3831IPEFGr54Gx/IyYzIr38aWKEZJBJ9hxentU9zzeRL1gayz6QuBG4GpA4Ue25db8vEKVe7UdpJtBfWY="
    - secure: "IPI+o9gMiaBL4e5U3U8uwRpdjh/Lf/xNsQec6gnlQaNCsh/XWFJubcOqyo8gZOOGq7DSrVxOYViquvdRnK1m+bHaR/bIQi+tXRDxyfp361GT1PQ074pTauYoNjx1C7hjQDD4WwJF5zgTUIjgo8dkC8bB/CBpN7gt8FrQzUy9hCujD6oPDMC7tfkxyyeWRiwmr6bIuZCeondl8x+8+aZIVd6H1X4hBOjDV+sg0LcMs+cuUCtSDZ1Rgwtf3GArWDm8KKXLk03B2ebPT/Zq4ng9xp54u2zoLwfKO0EixSFXmDltCVzfZ4tuFGGdl4lSiDAX+OiMk01S+9cTokIPjeMLivtPjqR2DAph51CcRABiBwdCD3B9saorRldWt1oPTL44nDI6tfahphrfofGCSpJAJMaT+DIn4L7p2ymUvYG5kelsADhLd4bFP/xavntmGHUo+/3TTZpOblo3DuBq84PNWNhc01fr7trP6c0j5ND8CepPPINZg7pqFUweUUur1EyzoELsP3U89EGGPHmrEnwEoUD6LezBHpIe/2N82joCyL3Le6bKNjAiemDq9p98x91VFlczbKoBWZfEzr+b2LrzpQBDcFcY42FyM6u/clHMIstsNHUT//4sJtVD0ykNnqV4OrfQI9y8tG8OQz8tXBHWTZrn0ZhILOsNxnwnPaVwisM="
    - secure: "pODMsHkw3sGDGRgOANn03Z23pTouDJrb4pA1iUexaXU7f4944L5pE+6eL31Y4n/wzgCyvTW8zfn8qaXy76BvuPzkKUQ5qQDccXuKs/gJD93W5FwBcVlL39/cC1lOWDutQh83ksQb36/ybKFPRPXHc6yo5W3SLH58dTyFYJuq/rDR0/ALRErD8wLzOMAA+Ed9Tpln+VIJLxjutQcdXISsctWGBzgzdc8yhXIMgi2c4WCkKBzZQBJQbclPUjpBdCNm38AJczZTIzEqzv66SV9GvZrozeeGwosn7dDF9BqH6TM7iA0aKuJIZRQ1QLa/vo67NtKcV+xJ1F4/qeyvzhtxr8VU6RZX7+/ajNJaXJVmm6ArhtdOVfX7/3vQ1zI9ItcKGPkhmxlJGsI2sCvylXwK+zPLhQuSkJ71zlA8l2I+6r5aFqjqZ0Dp0b6NbmZz9cE5WPcDUWlUyNQTVfdejJQ1gARvyvRxHyb4PLZMo6fjwhVxU/xu8ZmBXGg0xwsEwqHmIDSCVtKXNrLEskxd8GKruyQVym/QUhV4B4VdwHfi7fWINAjvf5047FInegnoLfHfu8CW12kZTo//E0MxKlZ2XdetcDwWLLHiMuxlWK5rsmU3ZHpZyvSv35bpeqlDTKN8YxWGU6G9RTCX5az70j4bUu/QsP5OB9JfDDeM6qDx2nA="
    - COMMIT=${TRAVIS_COMMIT::7}
script:
  - ./mvnw clean install -B
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
  - export IMAGE_NAME=myapi/main-repo
  - docker build -t $IMAGE_NAME:latest .
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: myapi-api