dist: trusty
jdk: oraclejdk8
language: java
sudo: true
services:
  - postgresql
  - docker
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
env:
  global:
    - secure: "kO50lHwXVtLY+hmCrKmqAO+ZUjslvQK28uLTEUEhSgA7IEU9uyGH+fnSlm1W0RgfBgiz7hiZloh2obk/n9cmpSpLurzHOUvsunKhawfzHBmVheSvWyeIZfwRxFhmK+/m9114cKf9rj82vHukFYnCcJU4h2F02CV8SDFKWFek2HVQ/hzut+2J4NRLIfdfO6iSlHO0Vv4dIrOC/6h6nq+dtRjmzTf3lnFCPsdNUHq47XAZrz4agFuYylJTlBdzcJYPp+hPik3jK+Z4lc70BDGyd+GU/PU64TpuM4mrQDAGtTerSG0o3lAjlIiZbP/Yxlj1V0+HKr5yk0UI/VmvBWO/6T0CPKU9V5Wbx7c2tHqyX8Dz4Mv4xdKbc5O6v2uJw9X98Dxa8Kv31nca+4MWvIqUivoouanBN+1QWbSBCfz/j0jzmr/zBZImWorAe9uY8XHpGUD3w6BoYzO1V/p98E1ksV/aA7kW3YB+ePKyioUjRkgOD7/4xjKyK+SclxaC02J3vtgmK2pQia6uvH7m8Na36b1GNqyaUwgjEzMFCxeOAG6wDYPGQcOtN6lvzemQYbCo5iiZcfZEJAoPyewPx9Ah/6dSFwGdqoCyIti+RKt+dq38bZg9zCZP5UnOKN7m/3lkKxxo1m/1onWJF/OvGAIeyZmbHucuk8uPGVPLZ99QSRw="
    - secure: "mBW5nT1FDU7m8H3tdmVl9jd7VjOiX6fnJNIIDQ6RINdNhHnYiXz7At9ugKshFb2XQb2j4B7qi9kjUVXHpMaVQ/Ybg8HoewtvF2yAH7yBEA2VbdQZzpDZ9Ehk2SEMqPab1tLoiqxWrBWQL6H/dPT6Tk8R7xH6W6aoQw/ngl9WJDpur+o+rBb9MEAB5CIinKVz0kJWGmHkch21nb75tuhs6Qf7xmZ/82eYhLHzhpHe7H6Gq5Cfi+EfnIMCpp77LR/iP1UaWqZs6589XTB208IDXsH2nwUsWquv6K5/lgCf/MZhgr3KOU7gbOG5Wn1xTEJrjzN1A85TPteWJTS6Thv95/wyIXSDP3qS8WIH6oURWDwn8iET3QnEy6wbvS8l/ouY+/rgPepWr2ybZaistCF/fHJ1Af5brcR//LvOxeCZoxgVokMa97+sPzvsDoJSHMnFl/eMdtVzWhDTPilJswL1VjlxwB21a/HfMkp5exu9NGKsZTGnB7NJU/o+wr0T8olps236ZsEIGUzlnZPemlXjLTlPBQhRrvixIJZmIBxMmQbJMtndVpTI65FPIlgctfyjNwomQPwrY9Xjrfic9KwsU3JntXehurwk7kRYr6D6UcfHUSN2U8LxgvGR2KXxLhSrJhneWFzUDmTuxknBU2k/AXYgUAb4LVmDgdM4kM+MliM="
    - secure: "V7Rp9lCEdwd/C+UYpIOvbbkErVlcY/SC8Dsocc5rOQ/F5QencoUPKf/VeQqxUvdD5ayjT1x81FXmTx9c3gVO7+1E5u1cv87Om+Oj1LyRtsBcw/Gh5ZOvAUz4CRvYwlhE+s/G6P2NbdTck61Y0cW7tNMHBiyh4qIIV4eUuYkY3GxtFXKQbjNiTs14tSD8Cnwc5C3Xx8/HeJgOBlu4bvBd8zYPys02Ac2acHXhmyXU8yhmQn4Q51FHBepnB95oruuh+/uuyuhDP54tXA60qjP2Lmq1ZzDrcZtCua/bTW0lqa64LQh4hsnIRdR+ixOiQIavMZU3hwXAmHiQv3n2PoIULsQjXQTYkkMLd9HdocriDODdY4VIahAYF2yMcW1vy7WJ7yCMe/6H2JkGlvrXjaULPIc4mF4LaAml8Vi2JMxomePQ0peRTfyk9OpkjNEtHa87pEel0CQoJDqiHuR7CwmBR2drx6s6uaVtoBRJtBuwtdRSA7p5btSbaSWjNnIRuOrDGaHqVTLJZfNwXNgKRipuwVL3FnHiUNJ0D0nGOPBb0XJBQyOFrAZ0uF3LaWqZtZeDneb3Lki80r+7YDF74lsG9+p/4yAIboMHORsH5WrbXwEkjT58DTrsjm7Jkt5eVSe1Pc5+RHvQBij/baqEHEM/+EGISUONBOFT5vvI/EsRx10="
    - COMMIT=${TRAVIS_COMMIT::7}
script:
  - ./mvnw clean install -B
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
  - export IMAGE_NAME=myapi/main-repo
  - docker build -t $IMAGE_NAME:latest .
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: myapi-api