dist: trusty
jdk: oraclejdk8
language: java
sudo: true
services:
  - postgresql
  - docker
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
env:
  global:
    - secure: "CHdpbLyiMyqJn/GTGo4kmUohKRI1QltOtO9nPMHOOTM5cr33D0M+WAh0dSM4AGZu53F6D32z3osDCdKzaybLR9dM5lOcXIXoO3PydN4OtzjwYxgUA728Jeq9Evx6+3Q8ACOWA0ldfIAriWIlohD7XW8XxUQNCehS4MccvFmtHFbW9bBgcm8YRiys9w1vd3v5xWoqwNUEdTnVHFsu4gNJL5PduNeuRFYhwGVGaLWQAIt+fQdayuon7Q/qOBCM2Kj/7MG2kakrHCaEcVX9We/r7d0FPvwU3hdnTKyUutaosF+507OmufI2mh2wtApvc8v0A/5Yx8i+FyHHiP62Bpai6vFaXDefkDk2Iv7f7tg7ZfJYC6x77vWYrxEna3DzijcXLAiIzmoGvhr/8wtnoOS2I3/+PsAO4FsTqlKEsG83FIw4rrQt6Q1KrRU1ie+CIXzuht2wjV/r1exPlWOzfSIetCbxxdIxz7NqoARbFzPcMhauZAa9FaeSxS4e0Ihf2uOLmzXVB7YsubdNZCkUIhHMcitRcwqOsssznE3oZL5qt8slDv5AubnDPySqCeMztr5O7cJBH08DiHIFgf58EYtkq5E+RX8vyq/41NRvaKfAuSJiJamQDClOymAFW9sMC6Kt01L8AdaOV4AyOgpPNbfiq8cQLaN72Vwc6CXY54eW364="
    - secure: "i15E4gUOXKngDFxKRHwth5P5X9XYnVwqPdrQ4cvqnbs99kIxVbvtHKrHcE/8fcTQX9vYm3oDV1xodYROckOIXaF2cfpVRXxoc5t2IioDUby0we+N/Oy4pftCJD5ZO1YbgtmWW8rLKXbkaLb+BoAU8WHRLrND3xryWn1Ez7da2YTVy0v0xH/vVKjeQnB57xWTBJouuJ8co3pcI7wcthuN1ZNVOUYf7UGxb6YuMO7NGKhNsgnaTvCeVcWwIK4LQ3pECwa38A4DDuJg6Hpu40969OpoKjkJWLTnXuvLR3OJtxN8K8r29ZqQMAvzNKp1X5t6OpubSEiE2UeIRfJ6Bvd68y1bQBmzKKzu0Bo2yT20ufaEjg9hZ+lHJBGzcOhlLwS0aT9IwtcxhygL+eQOJ4vQkGmzVia/zuqy9bPmYGPQ3xMlPEsXIr9VwrBht8Yw3lVVXk7cNZXTULubVUUV2aFd0BDcNHdnP5pofqEsKgJx8grHv2YgwH3v+VLopWrvuYKJ9kfJmWQd6lWnRQ9vXief9qMAujG4vdlD83D7S9EceXFT8JGW34/P3XEPjz1s0dqQQ2CkWBlkCXkAUnkv32t5Y+7qnWA5AA/ViVAHFZM8oAM2eWEMwZIlN+epSZR9HPWEAe7+1g3K2t4oKFBZwEchYMHPmTfcYQFG0nGrATLIz+I="
    - secure: "SkycAjEHxGy8ibyH3oik8831ZIu6VahnoI0AuqnpP1Ly2DkwSkVK2gD8ZhVsL5jVZB4UP0nkmn+hP7PqvtVsiIY4mt1S8E1BQSPPL4gdB0qUemIoSOCGdW2/5zAxZMCZfTM2j6y2sV/MbWfGy4nMZLQD0lTRzq3TmJkS7McAaYAgW8DlUy1CS69lXsHdWyKx5D+taihhiWnOkFApA37Xak8Psr0DuwzsM5Q6EOUbDBJAOs2bEYpDu1chVqjb/6IDc5ljFDe42UQ4K/aTPs2GwGeXWzpKrYIrHyD137E63Jc7pDUhmiX9u0N7Ex50+j/nGR7ass4IXH8SmLzMKYX/ngJOgRld2fT8Q3JX8iMg02HvJ8chlBDLdKmF351HFsuJO5iM4VgJNEmWNlN5tyHK3QGTtHUHk7evPu8mu+plfecJqi3/GZV9OZaRqebS78q00/AXq0R9Te51Ta5P3qqMKuGqnV4VWjQVKZRGURV3bci4rONoug8P1LIeOG5oY9ankvAbijYNPArVQjpJiJb6AmtDA9Tyvyoj8Hu69c7h7F6Xr2s022yF1jIPxSYjDEgm9rZMoT2I+/uP4FSSJB1plBEBq2M9A5EXRZU8KR1AbuUlRHy39xzrx62ZsDZoS7RLDLVZH2+dIW3q3h27qXN3FC7FqngYfUQ0hiS6tbiUU6c="
    - COMMIT=${TRAVIS_COMMIT::7}
script:
  - ./mvnw clean install -B
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
  - export IMAGE_NAME=myapi/main-repo
  - docker build -t $IMAGE_NAME:latest .
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: myapi-api