 dist: trusty
 jdk: oraclejdk8
 language: java
 sudo: true
 services:
   - postgresql
   - docker
 addons:
    apt:
       packages:
          - oracle-java8-installer
 before_install:
    - chmod +x mvnw