DROP TABLE IF EXISTS drivers CASCADE;
DROP SEQUENCE IF EXISTS global_seq;

CREATE SEQUENCE global_seq START WITH 1;

CREATE TABLE DRIVERS
(
    ID INTEGER PRIMARY KEY DEFAULT nextval('global_seq'),
    LAST_NAME  VARCHAR NOT NULL,
    FIRST_NAME VARCHAR NOT NULL,
    MID_NAME   VARCHAR,
    PHONE      VARCHAR,
    RATING     INTEGER
)